### ISSUE TITLE
installation on macos 10.13 (High Sierra)

### ISSUE THREAD

**Issue by rmaldersoniii** [PDP-10/klh10#47]
I have an issue building kn10-kl on High Sierra: A number of places have an interrupted format string in a write to a log file, and the compiler complains about a missing ")" at the end of the first part of the string. I will freely admit that I am using the original Panda distribution, which build just fine in 2011 on whatever generation of OS X that was, but the binaries will not run under High Sierra so I have to rebuild.

Has this been fixed in the Github variant? Or is there a known fix which I am missing?

This was easier when I had numerous Linux and BSD systems lying around the museum; now I'm stuck with my home resources

Secondarily, has anyone created an Xcode project to build KLH10 natively on the Mac?

Thanks,
Rich

Rich Alderson
ex Living Computers: Museum + Labs

**Comment by larsbrinkhoff** [comment]
I don't recall any problem with, or fixes for, format strings.

No one has come forward with an Xcode project.  In general, support for macOS is somewhat lacking, because none of the regulars are running that system.

**Comment by rmaldersoniii** [comment]
While looking into the Makefile -> Xcode question, I ran across something which pointed out that gcc is C89 compliant, while LLVM clang is C99 compliant.

The last time I built any part of KLH10, I was using gcc, but these days, the default on macos is clang. Exporting "CC=/usr/bin/gcc" before running the makefile resulted in a successful compilation.

I'll pursue the Xcode thing in my spare time; I'm starting work on a contract on Monday, so it will be low priority. I note that there is still a richalderson fork, although you merged all my changes into the master years ago, so the fork is like 145 changes out of date. Remind me of the HOWTO for updating the fork from the master, and I'll do things from there.

Thanks,
Rich

**Comment by larsbrinkhoff** [comment]
richalderson is a branch, not a fork.  I assume there's nothing valuable on the branch.  I probably created it, so I'll go ahead and claim there probably isn't.  Assuming this is true, the steps to make it up to date would be:

1. git fetch ;to make sure your local clone is updated
2. git checkout richalderson
3. git reset --hard origin/master ;this will destroy the old branch, so beware
4. git push ;to update GitHub

**Comment by larsbrinkhoff** [comment]
Hmm, it looks like @Rhialto created the richalderson branch.  Do you think that commit has been merged, so the branch can be reused?

**Comment by Rhialto** [comment]
Going by the commit message (since this is something I totally don't remember any more), this branch is a place to put the changes that I found at http://www.panix.com/~alderson/klh10-2.0h_for_OSX.6.8/ .
A quick look suggests that all the changes are merged in one way or another, or are possibly no longer relevant.
If Rich wants, he is totally free to destroy the branch and create another.

**Comment by rmaldersoniii** [comment]
Sorry, I misremembered the Git terminology. "Fork" to me means "process", a legacy of decades on the architecture.

There is supposedly 1 outstanding difference between the richalderson branch and the master on the richalderson side. It's probably nothing, but I wanted to check before nuking it.

I'll leave it to Rhialto to decide, since he did the work, and just create a new branch for the Xcode stuff.

**Comment by Rhialto** [comment]
The changes I see in the patches are as follows, and they all seem to be present in current code:
- make the lights configurable. Maybe this is currently not done in exactly the same way, but effectively the change was applied.
- some makefile changes which is moot since they are quite different now anyway
- `PC_ADDXCT` fix to avoid multiple assignments to the same variable between sequence points (if I recall the root cause correctly)
- remove some `register` keywords, if I recall correctly, because the address of the variables was taken somewhere so it's not a possible combination
- and finally one replacement of a magic constant 0600 by nicely #defined names
